// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module generic_fmax_float_s (
        ap_ready,
        x,
        y,
        ap_return
);


output   ap_ready;
input  [31:0] x;
input  [31:0] y;
output  [31:0] ap_return;

wire   [31:0] t_V_1_fu_42_p1;
wire   [31:0] t_V_2_fu_68_p1;
wire   [7:0] tmp_V_fu_54_p4;
wire   [22:0] tmp_V_1_fu_64_p1;
wire   [7:0] tmp_V_2_fu_80_p4;
wire   [22:0] tmp_V_3_fu_90_p1;
wire   [0:0] tmp_3_fu_100_p2;
wire   [0:0] tmp_4_fu_106_p2;
wire   [0:0] tmp_fu_94_p2;
wire   [0:0] tmp_5_fu_112_p2;
wire   [0:0] tmp2_fu_124_p2;
wire   [0:0] tmp1_fu_118_p2;
wire   [0:0] tmp_i_fu_136_p2;
wire   [0:0] tmp_1_i_fu_142_p2;
wire   [0:0] tmp_i1_fu_154_p2;
wire   [0:0] tmp_1_i1_fu_160_p2;
wire   [0:0] p_Result_s_fu_46_p3;
reg   [22:0] p_Result_7_fu_172_p4;
wire   [31:0] p_Result_8_fu_182_p4;
wire   [0:0] ymaggreater_fu_196_p2;
wire   [0:0] ymaggreater_1_fu_202_p2;
wire   [0:0] p_Result_6_fu_72_p3;
wire   [0:0] p_s_fu_208_p3;
wire   [0:0] ymaggreater2_fu_216_p3;
wire   [0:0] or_cond2_fu_130_p2;
wire   [0:0] tmp_7_demorgan_fu_148_p2;
wire   [0:0] sel_tmp_fu_232_p2;
wire   [0:0] sel_tmp1_fu_238_p2;
wire   [0:0] tmp_9_demorgan_fu_166_p2;
wire   [0:0] sel_tmp2_fu_244_p2;
wire   [31:0] res_fu_192_p1;
wire   [31:0] res_1_fu_224_p3;
wire   [0:0] sel_tmp6_demorgan_fu_258_p2;
wire   [0:0] sel_tmp6_fu_264_p2;
wire   [0:0] sel_tmp7_fu_270_p2;
wire   [31:0] res_2_fu_250_p3;
wire   [0:0] sel_tmp11_demorgan_fu_284_p2;
wire   [0:0] sel_tmp3_fu_290_p2;
wire   [0:0] sel_tmp4_fu_296_p2;
wire   [31:0] res_4_fu_276_p3;
wire   [31:0] res_5_fu_302_p3;

assign ap_ready = 1'b1;

assign ap_return = ((or_cond2_fu_130_p2[0:0] === 1'b1) ? y : res_5_fu_302_p3);

assign or_cond2_fu_130_p2 = (tmp2_fu_124_p2 & tmp1_fu_118_p2);

assign p_Result_6_fu_72_p3 = t_V_2_fu_68_p1[32'd31];

always @ (*) begin
    p_Result_7_fu_172_p4 = tmp_V_1_fu_64_p1;
    p_Result_7_fu_172_p4[32'd22] = |(1'd1);
end

assign p_Result_8_fu_182_p4 = {{{p_Result_s_fu_46_p3}, {8'd255}}, {p_Result_7_fu_172_p4}};

assign p_Result_s_fu_46_p3 = t_V_1_fu_42_p1[32'd31];

assign p_s_fu_208_p3 = ((p_Result_s_fu_46_p3[0:0] === 1'b1) ? ymaggreater_1_fu_202_p2 : ymaggreater_fu_196_p2);

assign res_1_fu_224_p3 = ((ymaggreater2_fu_216_p3[0:0] === 1'b1) ? y : x);

assign res_2_fu_250_p3 = ((sel_tmp2_fu_244_p2[0:0] === 1'b1) ? res_fu_192_p1 : res_1_fu_224_p3);

assign res_4_fu_276_p3 = ((sel_tmp7_fu_270_p2[0:0] === 1'b1) ? y : res_2_fu_250_p3);

assign res_5_fu_302_p3 = ((sel_tmp4_fu_296_p2[0:0] === 1'b1) ? x : res_4_fu_276_p3);

assign res_fu_192_p1 = p_Result_8_fu_182_p4;

assign sel_tmp11_demorgan_fu_284_p2 = (tmp_7_demorgan_fu_148_p2 | or_cond2_fu_130_p2);

assign sel_tmp1_fu_238_p2 = (tmp_7_demorgan_fu_148_p2 & sel_tmp_fu_232_p2);

assign sel_tmp2_fu_244_p2 = (tmp_9_demorgan_fu_166_p2 & sel_tmp1_fu_238_p2);

assign sel_tmp3_fu_290_p2 = (sel_tmp11_demorgan_fu_284_p2 ^ 1'd1);

assign sel_tmp4_fu_296_p2 = (tmp_9_demorgan_fu_166_p2 & sel_tmp3_fu_290_p2);

assign sel_tmp6_demorgan_fu_258_p2 = (tmp_i1_fu_154_p2 & tmp_1_i1_fu_160_p2);

assign sel_tmp6_fu_264_p2 = (sel_tmp6_demorgan_fu_258_p2 ^ 1'd1);

assign sel_tmp7_fu_270_p2 = (sel_tmp6_fu_264_p2 & sel_tmp1_fu_238_p2);

assign sel_tmp_fu_232_p2 = (or_cond2_fu_130_p2 ^ 1'd1);

assign t_V_1_fu_42_p1 = x;

assign t_V_2_fu_68_p1 = y;

assign tmp1_fu_118_p2 = (tmp_4_fu_106_p2 & tmp_3_fu_100_p2);

assign tmp2_fu_124_p2 = (tmp_fu_94_p2 & tmp_5_fu_112_p2);

assign tmp_1_i1_fu_160_p2 = ((tmp_V_3_fu_90_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_1_i_fu_142_p2 = ((tmp_V_1_fu_64_p1 != 23'd0) ? 1'b1 : 1'b0);

assign tmp_3_fu_100_p2 = ((tmp_V_1_fu_64_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_4_fu_106_p2 = ((tmp_V_2_fu_80_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_5_fu_112_p2 = ((tmp_V_3_fu_90_p1 == 23'd0) ? 1'b1 : 1'b0);

assign tmp_7_demorgan_fu_148_p2 = (tmp_i_fu_136_p2 & tmp_1_i_fu_142_p2);

assign tmp_9_demorgan_fu_166_p2 = (tmp_i1_fu_154_p2 & tmp_1_i1_fu_160_p2);

assign tmp_V_1_fu_64_p1 = t_V_1_fu_42_p1[22:0];

assign tmp_V_2_fu_80_p4 = {{t_V_2_fu_68_p1[30:23]}};

assign tmp_V_3_fu_90_p1 = t_V_2_fu_68_p1[22:0];

assign tmp_V_fu_54_p4 = {{t_V_1_fu_42_p1[30:23]}};

assign tmp_fu_94_p2 = ((tmp_V_fu_54_p4 == 8'd0) ? 1'b1 : 1'b0);

assign tmp_i1_fu_154_p2 = ((tmp_V_2_fu_80_p4 == 8'd255) ? 1'b1 : 1'b0);

assign tmp_i_fu_136_p2 = ((tmp_V_fu_54_p4 == 8'd255) ? 1'b1 : 1'b0);

assign ymaggreater2_fu_216_p3 = ((p_Result_6_fu_72_p3[0:0] === 1'b1) ? p_s_fu_208_p3 : ymaggreater_fu_196_p2);

assign ymaggreater_1_fu_202_p2 = (ymaggreater_fu_196_p2 ^ 1'd1);

assign ymaggreater_fu_196_p2 = (($signed(t_V_1_fu_42_p1) < $signed(t_V_2_fu_68_p1)) ? 1'b1 : 1'b0);

endmodule //generic_fmax_float_s
