-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity generic_fmax_float_s is
port (
    ap_ready : OUT STD_LOGIC;
    x : IN STD_LOGIC_VECTOR (31 downto 0);
    y : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of generic_fmax_float_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";
    constant ap_const_lv32_1E : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011110";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv23_0 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000000000000000";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal t_V_1_fu_42_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_2_fu_68_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_V_fu_54_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_V_1_fu_64_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_V_2_fu_80_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_V_3_fu_90_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_3_fu_100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_106_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_94_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_fu_112_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp2_fu_124_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp1_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i_fu_142_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_i1_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_i1_fu_160_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_s_fu_46_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_7_fu_172_p4 : STD_LOGIC_VECTOR (22 downto 0);
    signal p_Result_8_fu_182_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ymaggreater_fu_196_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ymaggreater_1_fu_202_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Result_6_fu_72_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_s_fu_208_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ymaggreater2_fu_216_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_cond2_fu_130_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_demorgan_fu_148_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp_fu_232_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp1_fu_238_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_demorgan_fu_166_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp2_fu_244_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_fu_192_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_1_fu_224_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp6_demorgan_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp6_fu_264_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp7_fu_270_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_2_fu_250_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal sel_tmp11_demorgan_fu_284_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp3_fu_290_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sel_tmp4_fu_296_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal res_4_fu_276_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal res_5_fu_302_p3 : STD_LOGIC_VECTOR (31 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return <= 
        y when (or_cond2_fu_130_p2(0) = '1') else 
        res_5_fu_302_p3;
    or_cond2_fu_130_p2 <= (tmp2_fu_124_p2 and tmp1_fu_118_p2);
    p_Result_6_fu_72_p3 <= t_V_2_fu_68_p1(31 downto 31);
    
    p_Result_7_fu_172_p4_proc : process(tmp_V_1_fu_64_p1)
    begin
        p_Result_7_fu_172_p4 <= tmp_V_1_fu_64_p1;
        p_Result_7_fu_172_p4(22) <= ap_const_lv1_1(0);
    end process;

    p_Result_8_fu_182_p4 <= ((p_Result_s_fu_46_p3 & ap_const_lv8_FF) & p_Result_7_fu_172_p4);
    p_Result_s_fu_46_p3 <= t_V_1_fu_42_p1(31 downto 31);
    p_s_fu_208_p3 <= 
        ymaggreater_1_fu_202_p2 when (p_Result_s_fu_46_p3(0) = '1') else 
        ymaggreater_fu_196_p2;
    res_1_fu_224_p3 <= 
        y when (ymaggreater2_fu_216_p3(0) = '1') else 
        x;
    res_2_fu_250_p3 <= 
        res_fu_192_p1 when (sel_tmp2_fu_244_p2(0) = '1') else 
        res_1_fu_224_p3;
    res_4_fu_276_p3 <= 
        y when (sel_tmp7_fu_270_p2(0) = '1') else 
        res_2_fu_250_p3;
    res_5_fu_302_p3 <= 
        x when (sel_tmp4_fu_296_p2(0) = '1') else 
        res_4_fu_276_p3;
    res_fu_192_p1 <= p_Result_8_fu_182_p4;
    sel_tmp11_demorgan_fu_284_p2 <= (tmp_7_demorgan_fu_148_p2 or or_cond2_fu_130_p2);
    sel_tmp1_fu_238_p2 <= (tmp_7_demorgan_fu_148_p2 and sel_tmp_fu_232_p2);
    sel_tmp2_fu_244_p2 <= (tmp_9_demorgan_fu_166_p2 and sel_tmp1_fu_238_p2);
    sel_tmp3_fu_290_p2 <= (sel_tmp11_demorgan_fu_284_p2 xor ap_const_lv1_1);
    sel_tmp4_fu_296_p2 <= (tmp_9_demorgan_fu_166_p2 and sel_tmp3_fu_290_p2);
    sel_tmp6_demorgan_fu_258_p2 <= (tmp_i1_fu_154_p2 and tmp_1_i1_fu_160_p2);
    sel_tmp6_fu_264_p2 <= (sel_tmp6_demorgan_fu_258_p2 xor ap_const_lv1_1);
    sel_tmp7_fu_270_p2 <= (sel_tmp6_fu_264_p2 and sel_tmp1_fu_238_p2);
    sel_tmp_fu_232_p2 <= (or_cond2_fu_130_p2 xor ap_const_lv1_1);
    t_V_1_fu_42_p1 <= x;
    t_V_2_fu_68_p1 <= y;
    tmp1_fu_118_p2 <= (tmp_4_fu_106_p2 and tmp_3_fu_100_p2);
    tmp2_fu_124_p2 <= (tmp_fu_94_p2 and tmp_5_fu_112_p2);
    tmp_1_i1_fu_160_p2 <= "0" when (tmp_V_3_fu_90_p1 = ap_const_lv23_0) else "1";
    tmp_1_i_fu_142_p2 <= "0" when (tmp_V_1_fu_64_p1 = ap_const_lv23_0) else "1";
    tmp_3_fu_100_p2 <= "1" when (tmp_V_1_fu_64_p1 = ap_const_lv23_0) else "0";
    tmp_4_fu_106_p2 <= "1" when (tmp_V_2_fu_80_p4 = ap_const_lv8_0) else "0";
    tmp_5_fu_112_p2 <= "1" when (tmp_V_3_fu_90_p1 = ap_const_lv23_0) else "0";
    tmp_7_demorgan_fu_148_p2 <= (tmp_i_fu_136_p2 and tmp_1_i_fu_142_p2);
    tmp_9_demorgan_fu_166_p2 <= (tmp_i1_fu_154_p2 and tmp_1_i1_fu_160_p2);
    tmp_V_1_fu_64_p1 <= t_V_1_fu_42_p1(23 - 1 downto 0);
    tmp_V_2_fu_80_p4 <= t_V_2_fu_68_p1(30 downto 23);
    tmp_V_3_fu_90_p1 <= t_V_2_fu_68_p1(23 - 1 downto 0);
    tmp_V_fu_54_p4 <= t_V_1_fu_42_p1(30 downto 23);
    tmp_fu_94_p2 <= "1" when (tmp_V_fu_54_p4 = ap_const_lv8_0) else "0";
    tmp_i1_fu_154_p2 <= "1" when (tmp_V_2_fu_80_p4 = ap_const_lv8_FF) else "0";
    tmp_i_fu_136_p2 <= "1" when (tmp_V_fu_54_p4 = ap_const_lv8_FF) else "0";
    ymaggreater2_fu_216_p3 <= 
        p_s_fu_208_p3 when (p_Result_6_fu_72_p3(0) = '1') else 
        ymaggreater_fu_196_p2;
    ymaggreater_1_fu_202_p2 <= (ymaggreater_fu_196_p2 xor ap_const_lv1_1);
    ymaggreater_fu_196_p2 <= "1" when (signed(t_V_1_fu_42_p1) < signed(t_V_2_fu_68_p1)) else "0";
end behav;
